const layers = [
    {
        name: '摄像头',
        typeGroupKey: 'camera',
        typeId: '121000100000',
    },
    {
        name: 'normalUser',
        typeGroupKey: 'gps',
        typeId: 'normalUser',
    },
    {
        name: 'ambulance',
        typeGroupKey: 'gps',
        typeId: 'ambulance',
    },
    {
        name: 'policecar',
        typeGroupKey: 'gps',
        typeId: 'policecar',
    },
    {
        name: 'firetruck',
        typeGroupKey: 'gps',
        typeId: 'firetruck',
    },
    {
        name: '交通事故',
        typeGroupKey: 'event',
        typeId: '600700100010',
    },
    {
        name: '测试类型',
        typeGroupKey: 'event',
        typeId: '600700100011',
    },
    {
        name: '自然灾害',
        typeGroupKey: 'event',
        typeId: '600700100012',
    },
    {
        name: '环境瓦斯',
        typeGroupKey: 'event',
        typeId: '600700100013',
    },
    {
        name: '一氧化碳',
        typeGroupKey: 'event',
        typeId: '600700100014',
    },
    {
        name: '疫情设施类型',
        typeGroupKey: 'facility',
        typeId: '406000100001',
        analysisType: null,
    },
    {
        name: '类型001',
        typeGroupKey: 'facility',
        typeId: '406000100004',
        analysisType: null,
    },
    {
        name: '油气罐站',
        typeGroupKey: 'facility',
        typeId: '406000100020',
        analysisType: 'DangerousSource',
    },
    {
        name: '化工厂',
        typeGroupKey: 'facility',
        typeId: '406000100021',
        analysisType: 'DangerousSource',
    },
    {
        name: '燃气站',
        typeGroupKey: 'facility',
        typeId: '406000100022',
        analysisType: 'DangerousSource',
    },
    {
        name: '保护单位',
        typeGroupKey: 'facility',
        typeId: '406000100024',
        analysisType: 'KeyProtection',
    },
    {
        name: '学校',
        typeGroupKey: 'facility',
        typeId: '406000100025',
        analysisType: 'KeyProtection',
    },
    {
        name: '污染源',
        typeGroupKey: 'facility',
        typeId: '406000100026',
        analysisType: 'PollutionSource',
    },
    {
        name: '避难场所',
        typeGroupKey: 'facility',
        typeId: '406000100027',
        analysisType: 'Shelter',
    },
    {
        name: '仓库',
        typeGroupKey: 'facility',
        typeId: '406000100028',
        analysisType: 'Warehouse',
    },
    {
        name: '医疗资源',
        typeGroupKey: 'facility',
        typeId: '406000100029',
        analysisType: 'MedicalResource',
    },
    {
        name: '人力资源',
        typeGroupKey: 'facility',
        typeId: '406000100030',
        analysisType: 'ManpowerResource',
    },
    {
        name: '政府机构',
        typeGroupKey: 'facility',
        typeId: '406000100032',
        analysisType: null,
    },
    {
        name: '警力',
        typeGroupKey: 'facility',
        typeId: '406000100033',
        analysisType: 'ManpowerResource',
    },
    {
        name: '食品',
        typeGroupKey: 'facility',
        typeId: '406000100034',
        analysisType: 'EmergencySupply',
    },
    {
        name: '救援车辆',
        typeGroupKey: 'facility',
        typeId: '406000100035',
        analysisType: 'EmergencySupply',
    },
    {
        name: '其它',
        typeGroupKey: 'facility',
        typeId: '406000100036',
        analysisType: 'EmergencySupply',
    },
    {
        name: '基站',
        typeGroupKey: 'facility',
        typeId: '406000100037',
        analysisType: null,
    },
    {
        name: '广播',
        typeGroupKey: 'facility',
        typeId: '406000100038',
        analysisType: null,
    },
    {
        name: '摄像头',
        typeGroupKey: 'facility',
        typeId: '406000100039',
        analysisType: null,
    },
    {
        name: '鞭炮厂',
        typeGroupKey: 'facility',
        typeId: '406000100040',
        analysisType: 'DangerousSource',
    },
    {
        name: '加油站',
        typeGroupKey: 'facility',
        typeId: '406000100041',
        analysisType: 'DangerousSource',
    },
    {
        name: '氯气厂',
        typeGroupKey: 'facility',
        typeId: '406000100042',
        analysisType: 'DangerousSource',
    },
    {
        name: '烟花厂',
        typeGroupKey: 'facility',
        typeId: '406000100043',
        analysisType: 'DangerousSource',
    },
    {
        name: '氢气运输站',
        typeGroupKey: 'facility',
        typeId: '406000100044',
        analysisType: 'DangerousSource',
    },
    {
        name: '公安',
        typeGroupKey: 'facility',
        typeId: '406000100045',
        analysisType: 'ManpowerResource',
    },
    {
        name: '测试设置111',
        typeGroupKey: 'facility',
        typeId: '406000100046',
        analysisType: null,
    },
    {
        name: '雨量监测点',
        typeGroupKey: 'facility',
        typeId: '406000100047',
        analysisType: 'RainfallPoint',
    },
    {
        name: '易涝点',
        typeGroupKey: 'facility',
        typeId: '406000100048',
        analysisType: 'FloodPoint',
    },
];

export default layers;
